version: '3.1'

services:
  stats-server:
    container_name: stats-server
    build: ewm-stats-service/service
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/statistics
      - SPRING_DATASOURCE_USERNAME=test
      - SPRING_DATASOURCE_PASSWORD=test
      - MAIN-SERVICE_URL=http://localhost:8080


  stats-db:
    image: postgres:latest
    container_name: stats-db
    volumes:
      - /var/lib/postgresql/data/
    ports:
      - "5431:5431"
    environment:
      - POSTGRES_DB=statistics
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test

  ewm-db:
    image: postgres:latest
    container_name: ewm-db
    expose:
      - "5432"
    volumes:
      - /var/lib/postgresql/data/
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=main_database
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test

  ewm-service:
    container_name: ewm-service
    build: ewm-main-service
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
      - stats-server
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/main_database
      - SPRING_DATASOURCE_USERNAME=test
      - SPRING_DATASOURCE_PASSWORD=test
      - STATS-SERVICE_URL=http://localhost:9090
